// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'filter': string;
  'next-sr-only': string;
}
declare var cssExports: CssExports;
export = cssExports;
