// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'link': string;
  'next-sr-only': string;
  'pagination': string;
}
declare var cssExports: CssExports;
export = cssExports;
