// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'next-sr-only': string;
  'topButtons': string;
}
declare var cssExports: CssExports;
export = cssExports;
